name: 'rustup components nightly'
description: 'Find most recent nightly build with the requested component available'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  target:
    description: Rust target triple
    required: true
  component:
    description: Component to search
    required: true

output:
  toolchain:
    description: Nightly toolchain name
  command:
    description: Cargo command to call this component
runs:
  using: 'node12'
  main: 'dist/index.js'
